### PR TITLE
SPRINT-0 Home, Players, and Games have mocked data up and running

### PR DESCRIPTION
**Pull request by bealerj2260**
@SquallRocks @EricLiu1 @kevinisninja @thienmint 

I ended up finding a resource that shows you how to include react with static html and routing through flask. Since there was a Piazza post today about not being required to use react for this first part I went ahead and started using bootstrap templates and plugging in data and styling as I went. This is still very wip but I wanted to get a PR out I can start getting feedback and so master is no longer just a readme. 

PS. For whoever merges this, could you please select "squash and merge" and then delete the source branch? That way we keep to small units of work in their own branches and we preserve commit history. Thanks!

### CODE REVIEW

**Comment by bealerj2260** [comment]
[Make navbar component](https://trello.com/c/rcYBkBV4/17-make-navbar-component)

**Comment by bealerj2260** [comment]
[Make carousel](https://trello.com/c/NuNFbxIE/19-make-carousel)

**Comment by bealerj2260** [comment]
[Have navbar shown on every page](https://trello.com/c/TVzPl2Di/18-have-navbar-shown-on-every-page)

**Comment by bealerj2260** [comment]
[Make model component for iteration over grid](https://trello.com/c/m9SpyHQj/22-make-model-component-for-iteration-over-grid)

**Review by thien-vo — APPROVED** [review]
Looks good. Approved.

**Pull request merged**
